### PR TITLE
LSTM for PPOC

### PR DESCRIPTION
**Pull request by spacegoing**

### CODE REVIEW

**Comment by ShangtongZhang** [comment]
Hi Chang,

Thanks for your PR, I really appreciate it. Do you mind I merge it into the DAC branch? 
Because my philosophy is to only implement well-established algorithms in the master branch, making it easier for future refactoring. If I put all algorithms in my paper to the master, I guess I won't be able to maintain the repo. Every update will incur lots of regression issues.

Best,
Shangtong

**Comment by spacegoing** [comment]
Hi Shangtong,

Thanks for your comment and I 100% agree with that:D

I developed those code on master branch. I am not sure if it will work on DAC though.
I am currently on a trip and will double check once I back home.

Have a nice day:D

**Comment by ShangtongZhang** [comment]
Sorry I have to close it as I can't find a place for this PR.
On the one hand the DAC branch is my official code branch for the paper, so I'd prefer it to be left as it is.
On the other hand PPOC is a `bad` algorithm that I don't want to include it in master.
Thanks again for your contribution.

**Comment by spacegoing** [comment]
Hi Shangtong, no worries. Sorry I completely forgot about this :P

**Pull request closed without merging**
